Process command-line files according to config settings
inaka/elvis pull request #568
Opened 2022-03-30 20:56 UTC by jamesaimonetti

Previously, command-line files were forced to be processed
sequentially, regardless of any `parallel` setting.

Now the files are converted to elvis_files and included in the config
for regular processing.

Addresses https://github.com/inaka/elvis/issues/567

2022-03-30 20:58 UTC, jamesaimonetti commented
@elbrujohalcon first stab. Lifted the bits in `file_to_path` from `elvis_core;rock_this/2`; might be worth putting in elvis_file as a generic `elvis_file:from_filename/1` type function?

2022-03-31 08:48 UTC, elbrujohalcon requested changes
Your approach is fine with me. But if you want to create `elvis_file:from_filename/1`, that's even better… of course.

2022-03-31 08:48 UTC, elbrujohalcon commented on src/elvis.erl
> -            lists:map(fun(F) -> rock_one_song(F, Config) end, Files)
Shouldn't we remove `rock_one_song/2` entirely, too?

2024-09-16 12:58 UTC, elbrujohalcon approved these changes

2025-04-23 10:42 UTC, paulo-ferraz-oliveira approved these changes
CI's failing, but the general direction is good.

2026-03-02 22:36 UTC, paulo-ferraz-oliveira commented
Looks simpler, too. Unfortunately tests are failing. You can run `rebar3 test` locally, to check everything at once.

2026-03-03 01:06 UTC, paulo-ferraz-oliveira commented on src/elvis.erl
> -            case application:get_env(elvis, keep_rocking, false) of
Doesn't this mean the option will no longer be used?

2026-03-03 08:07 UTC, elbrujohalcon commented on src/elvis.erl
> -            case application:get_env(elvis, keep_rocking, false) of
Hank should detect that, shouldn't it?

2026-03-03 08:08 UTC, elbrujohalcon requested changes

2026-03-03 08:08 UTC, elbrujohalcon commented on src/elvis.erl
> +    Paths = [file_to_path(File) || File <:- Files],
Please don't use strict generators yet… We would like to support OTP26, 27, and 28 with the same release while possible.

2026-03-03 08:09 UTC, elbrujohalcon commented on src/elvis.erl
> +    Paths = [file_to_path(File) || File <:- Files],
Furthermore, I think this code will look better as…
```suggestion
    Paths = lists:map(fun file_to_path/1, Files),
```

2026-03-03 17:05 UTC, jamesaimonetti commented on src/elvis.erl
> +    Paths = [file_to_path(File) || File <:- Files],
yeah realizing that after the fact, when i saw OTP 28 build fail because of that I changed it, will use lists:map instead to avoid the backwards incompat

2026-03-03 17:39 UTC, elbrujohalcon approved these changes
LGTM, but I'm curious to see if we should do something else about `keep_rocking`.

2026-03-03 17:43 UTC, elbrujohalcon commented on src/elvis.erl
> -            case application:get_env(elvis, keep_rocking, false) of
I just checked and now I see what you mean… it needs to be removed not from configs but from _everywhere else_. That is:
* https://github.com/inaka/elvis/blob/fb4ef8d6aa6c5b25aab79145d2d2e5faf392318d/priv/zsh_completion/_elvis#L29
* https://github.com/inaka/elvis/blob/fb4ef8d6aa6c5b25aab79145d2d2e5faf392318d/priv/bash_completion/elvis#L34
* https://github.com/inaka/elvis/blob/fb4ef8d6aa6c5b25aab79145d2d2e5faf392318d/src/elvis.erl#L14
* https://github.com/inaka/elvis/blob/fb4ef8d6aa6c5b25aab79145d2d2e5faf392318d/src/elvis.erl#L99
* https://github.com/inaka/elvis/blob/fb4ef8d6aa6c5b25aab79145d2d2e5faf392318d/src/elvis.erl#L129-L131

2026-03-03 17:44 UTC, elbrujohalcon requested changes
Let's properly remove `keep_rocking` from everywhere.
You may choose to leave it as an command for CLI but print out a warning indicating that it's deprecated, but I wouldn't complain if you just remove it entirely.

2026-03-04 08:46 UTC, elbrujohalcon approved these changes

2026-03-04 08:46 UTC, merged